export const terms = `<h1 style="text-align: center;"><strong><br />Termos de Uso e Condi&ccedil;&otilde;es de Navega&ccedil;&atilde;o</strong></h1>
<p><strong><br />PORTAL MEU TRATOR USADO</strong></p>
<p>Bem-vindo ao&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>. A seguir apresentamos a voc&ecirc; (<strong>USU&Aacute;RIO</strong>) os Termos de Uso e Condi&ccedil;&otilde;es de Navega&ccedil;&atilde;o, documento que relaciona as principais regras que devem ser observadas e seguidas por todos que acessam o&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;ou utilizam suas funcionalidades.</p>
<p>Como condi&ccedil;&atilde;o para acesso e uso das funcionalidades exclusivas do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>, sobretudo a contrata&ccedil;&atilde;o de servi&ccedil;os oferecidos pela plataforma, &eacute; necess&aacute;rio criar uma conta de acesso, declarando o&nbsp;<strong>USU&Aacute;RIO</strong>&nbsp;que fez a leitura completa e atenta das regras deste documento e de sua Pol&iacute;tica de Privacidade, estando plenamente ciente e de acordo com elas, formalizando assim seu aceite.</p>
<ol>
<li><strong>Informa&ccedil;&otilde;es Gerais sobre o Portal</strong></li>
</ol>
<p>1.1. Este Portal &eacute; dedicado &agrave; publica&ccedil;&atilde;o de an&uacute;ncios de tratores e equipamentos agr&iacute;colas usados, com objetivo de alimentar estoques de concession&aacute;rias, revendedores e lojas, facilitando a realiza&ccedil;&atilde;o de neg&oacute;cios entre tais empresas.</p>
<p>1.1.1. As&nbsp;<strong>CONTAS DE ACESSO</strong>&nbsp;no&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;podem ser criadas somente por pessoas jur&iacute;dicas, produtores rurais, pessoas f&iacute;sicas, sendo que apenas pessoas f&iacute;sicas maiores de 18 anos poder&atilde;o operara-las.</p>
<p>1.1.2. A cria&ccedil;&atilde;o de&nbsp;<strong>CONTAS DE ACESSO&nbsp;</strong>a usu&aacute;rios pessoas f&iacute;sicas que desejarem avaliar e adquirir equipamentos &eacute; gratuita, no entanto, para que usu&aacute;rios pessoa jur&iacute;dica possam anunciar, comprar, vender ou avaliar equipamentos na plataforma o&nbsp;<strong>USU&Aacute;RIO&nbsp;</strong><strong>.</strong> Ap&oacute;s o cadastro um consultor far&aacute; o contato pr&eacute;vio com o USU&Aacute;RIO identificando suas necessidades e liberando definitivamente seu acesso ao <strong>PORTAL</strong>.</p>
<p>1.1.3. A&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;poder&aacute; alterar os crit&eacute;rios de elegibilidade de sua plataforma ou da realiza&ccedil;&atilde;o de atividades nela a qualquer momento. Tamb&eacute;m, possui a faculdade de se recusar a conceder conta de acesso a qualquer pessoa ou entidade que utilizar de forma fraudulenta ou de qualquer forma violar os Termos de Uso ou documento legal do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>.</p>
<p>1.2. Para acessar o&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;de forma segura &eacute; de inteira responsabilidade dos&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;dispor de servi&ccedil;o de conex&atilde;o &agrave; internet, com antiv&iacute;rus e&nbsp;<em>firewall</em>&nbsp;habilitados.</p>
<p>1.3. O&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;e suas funcionalidades s&atilde;o apresentadas aos&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;na maneira como est&atilde;o dispon&iacute;veis, podendo passar por constantes aprimoramentos e atualiza&ccedil;&otilde;es, obrigando-se o&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;a:</p>
<p>1.3.1. Preservar a funcionalidade do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>, com&nbsp;<em>links</em>&nbsp;n&atilde;o quebrados, utilizando&nbsp;<em>layout</em>&nbsp;que respeita a usabilidade e navegabilidade, sempre que poss&iacute;vel.</p>
<p>1.3.2. Exibir as funcionalidades de maneira clara, completa, precisa e suficiente de modo que exista a exata percep&ccedil;&atilde;o das opera&ccedil;&otilde;es realizadas.</p>
<p>1.3.3. Garantir, por meio do estado da t&eacute;cnica dispon&iacute;vel, o sigilo dos dados inseridos nas funcionalidades oferecidas no&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>, somente sendo acess&iacute;veis pela&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;e por quem o&nbsp;<strong>USU&Aacute;RIO</strong>&nbsp;consentir, al&eacute;m de si pr&oacute;prio.</p>
<p>1.3.4. Obter as licen&ccedil;as e autoriza&ccedil;&otilde;es necess&aacute;rias para a disponibiliza&ccedil;&atilde;o de conte&uacute;dos por meio do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>.</p>
<p>1.4. A&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;envida seus esfor&ccedil;os para a disponibilidade cont&iacute;nua e permanente do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>. No entanto, pode ocorrer, eventualmente, alguma indisponibilidade tempor&aacute;ria decorrente de manuten&ccedil;&atilde;o necess&aacute;ria ou mesmo gerada por motivo de for&ccedil;a maior, como desastres naturais, falhas ou colapsos nos sistemas centrais de comunica&ccedil;&atilde;o e acesso &agrave; internet ou fatos de terceiro que fogem de sua esfera de vigil&acirc;ncia e responsabilidade.</p>
<p>1.4.1. Se isso ocorrer, a&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;far&aacute; o que estiver ao seu alcance para restabelecer o acesso ao&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;o mais breve poss&iacute;vel, dentro das limita&ccedil;&otilde;es t&eacute;cnicas de seus servi&ccedil;os e servi&ccedil;os de terceiros, dos quais a&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;depende para ficar online.</p>
<p>1.5. Eventuais procedimentos de manuten&ccedil;&atilde;o ser&atilde;o informados por meio dos canais oficiais de comunica&ccedil;&atilde;o do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;(a exemplo, mas n&atilde;o se limitando, perfis oficiais nas m&iacute;dias sociais, telefone de atendimento ou e-mail), caso seja necess&aacute;rio que este fique indispon&iacute;vel por longos per&iacute;odos.</p>
<ol start="2">
<li><strong>Funcionalidades do Portal MEU TRATOR USADO</strong></li>
</ol>
<p>2.1. O&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;&eacute; aplica&ccedil;&atilde;o de internet com objetivos de facilitar a compra e venda de tratores e equipamentos agr&iacute;colas usados por meio de avalia&ccedil;&otilde;es realizadas nos tratores e equipamentos agr&iacute;colas anunciados por concession&aacute;rias ou revendedoras. Haver&aacute; ainda a possibilidade de avalia&ccedil;&atilde;o de tratores e equipamentos agr&iacute;colas de pessoas f&iacute;sicas com o objetivo de aquisi&ccedil;&atilde;o dos mesmos.</p>
<p>2.2. Nas avalia&ccedil;&otilde;es ser&atilde;o ofertados valores que atendam as condi&ccedil;&otilde;es de pre&ccedil;os m&aacute;ximos e m&iacute;nimos estipulados previamente pelo anunciante, para aquisi&ccedil;&atilde;o dos tratores e equipamentos agr&iacute;colas anunciados.</p>
<p>2.2.1. O&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;fornece ainda a funcionalidade &ldquo;Compre Agora&rdquo; por meio da qual o&nbsp;<strong>USU&Aacute;RIO</strong>&nbsp;envia avalia&ccedil;&atilde;o sobre um equipamento anunciado em que se presume sua verifica&ccedil;&atilde;o presencial na respectiva concession&aacute;ria, revenda ou loja.</p>
<p>2.2.2. Uma vez iniciado o &ldquo;Compre Agora&rdquo;, o an&uacute;ncio ficar&aacute; em estado de reserva e o&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;informar&aacute; aos&nbsp;<strong>USU&Aacute;RIOS&nbsp;</strong>que a oferta entrou em &ldquo;Compre Agora&rdquo; e, ap&oacute;s confirma&ccedil;&atilde;o pelo vendedor, o an&uacute;ncio ficar&aacute; em estado de vendido, para que n&atilde;o haja mais nenhuma oferta pelo mesmo.</p>
<p>2.3. Os&nbsp;<strong>USU&Aacute;RIOS&nbsp;</strong>poder&atilde;o adicionar an&uacute;ncios aos &ldquo;Meus Favoritos&rdquo;, para acompanh&aacute;-los com maior proximidade, ainda que n&atilde;o tenham sido avaliados por ele.</p>
<p>2.4. Cada&nbsp;<strong>USU&Aacute;RIO&nbsp;</strong>adota as pr&oacute;prias regras de neg&oacute;cio e a&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;n&atilde;o interfere em nenhum deles.</p>
<p>2.5. Entretanto, pelo acesso a an&uacute;ncios mais vantajosos, haver&aacute; pagamento de tarifa pelo&nbsp;<strong>USU&Aacute;RIO</strong>&nbsp;&agrave;&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;sempre que algum neg&oacute;cio for concretizado, cujo valor estar&aacute; descrito no pr&oacute;prio an&uacute;ncio de avalia&ccedil;&atilde;o.</p>
<p>2.5.1. Quando o&nbsp;<strong>USU&Aacute;RIO&nbsp;</strong>n&atilde;o realizar os pagamentos de maneira pontual, a&nbsp;<strong>Conta de Acesso&nbsp;</strong>poder&aacute; ser suspensa at&eacute; a devida regulariza&ccedil;&atilde;o dos pagamentos, aos quais incidir&atilde;o juros de 1% (um por cento) ao m&ecirc;s, calculados &ldquo;pro-rata&rdquo;, al&eacute;m de incidir corre&ccedil;&atilde;o monet&aacute;ria com base na Tabela Pr&aacute;tica do Tribunal de Justi&ccedil;a do Estado de S&atilde;o Paulo, devida desde a(s) data(s) do(s) vencimento at&eacute; a do efetivo pagamento, e juros de 1% ao m&ecirc;s, calculados proporcionalmente aos dias de atraso.</p>
<p>2.5.2. A&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;se reserva o direito de cobrar os valores devidos dos&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;inadimplentes nos termos da lei civil, podendo para tanto valer-se de todos os meios previstos na legisla&ccedil;&atilde;o, incluindo a inser&ccedil;&atilde;o dos dados do usu&aacute;rio em cadastros de restri&ccedil;&atilde;o ao cr&eacute;dito e promovendo a&ccedil;&otilde;es judiciais.</p>
<p>2.6. Todos os equipamentos usados s&atilde;o anunciados &ldquo;<strong>no estado em que se encontram</strong>&rdquo;, conforme a descri&ccedil;&atilde;o de cada an&uacute;ncio em seu check list e sem qualquer necessidade de garantia do fabricante, de funcionamento, reposi&ccedil;&atilde;o de pe&ccedil;as, entre outros.</p>
<p>2.6.1 O anunciante dever&aacute; inserir os an&uacute;ncios de equipamentos no&nbsp;<strong>PORTAL</strong>&nbsp;contendo imagens n&iacute;tidas, informa&ccedil;&atilde;o completa, correta, suficiente, adequada e precisa em rela&ccedil;&atilde;o &agrave; marca, modelo, ano, estado, pend&ecirc;ncias financeiras e demais caracter&iacute;sticas do equipamento anunciado al&eacute;m do checklist completo.</p>
<p>2.7. As informa&ccedil;&otilde;es indicativas de cada an&uacute;ncio s&atilde;o fornecidas exclusivamente pelos anunciantes e sob a sua total responsabilidade. A&nbsp;<strong>MEU TRATOR USADO N&Atilde;O</strong>&nbsp;se responsabiliza por informa&ccedil;&otilde;es equivocadas publicadas por seus&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;ou por eventuais frustra&ccedil;&otilde;es de expectativas pelos tratores e equipamentos agr&iacute;colas adquiridos. Por isso, o&nbsp;<strong>USU&Aacute;RIO</strong>&nbsp;interessado na compra deve adotar as devidas cautelas para constatar a proced&ecirc;ncia e estado do equipamento, ficando a&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;indene de qualquer imprecis&atilde;o, imperfei&ccedil;&atilde;o ou oculta&ccedil;&atilde;o neste sentido.</p>
<p>2.8. Todos os&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;t&ecirc;m ci&ecirc;ncia de que os equipamentos usados podem n&atilde;o estar funcionando para movimenta&ccedil;&atilde;o e a&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;n&atilde;o se responsabiliza por quaisquer defeitos mec&acirc;nicos, el&eacute;tricos, falta de componentes obrigat&oacute;rios, d&eacute;bitos que reca&iacute;rem sobre os equipamentos ofertados, entre outros.</p>
<ol start="3">
<li><strong>Das responsabilidades e obriga&ccedil;&otilde;es dos USU&Aacute;RIOS</strong></li>
</ol>
<p>3.1. Os&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;se obrigam a realizar navega&ccedil;&atilde;o &eacute;tica no&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>, adequada com os prop&oacute;sitos aqui estabelecidos, sempre respeitando as condi&ccedil;&otilde;es que regem a utiliza&ccedil;&atilde;o do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;e sua finalidade, sob pena de suportarem os &ocirc;nus dos atos praticados e terem a exclus&atilde;o da conta de acesso do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>.</p>
<p>3.2. Os&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;se comprometem a fornecer dados cadastrais corretos, completos e atualizados para que a&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;possa prestar seus servi&ccedil;os em conformidade com as leis e normas regulamentares em vigor, al&eacute;m de fornecer canal de contato apto a ser acionado pela&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;para o melhor cumprimento dos servi&ccedil;os, sob pena da aplica&ccedil;&atilde;o das penas da lei, de indenizar a quem causar dano e de ter a conta de acesso do presente&nbsp;<strong>Portal</strong>&nbsp;exclu&iacute;da.</p>
<p>3.3. Os&nbsp;<strong>USU&Aacute;RIOS&nbsp;</strong>que anunciarem tratores e equipamentos usados no&nbsp;<strong>Portal MEU TRATOR USADO</strong>&nbsp;se responsabilizam para todos os fins previstos na legisla&ccedil;&atilde;o, incluindo, mas n&atilde;o se limitando, a eventuais v&iacute;cios, aparentes ou ocultos nos equipamentos anunciados.</p>
<p>3.4. &Eacute; de responsabilidade dos&nbsp;<strong>USU&Aacute;RIOS&nbsp;</strong>deixar seus sistemas de&nbsp;anti-spam, filtros similares ou configura&ccedil;&otilde;es de redirecionamento de mensagens ajustados de modo que n&atilde;o interfiram no recebimento dos comunicados e materiais da&nbsp;<strong>MEU TRATOR USADO</strong>, n&atilde;o sendo aceit&aacute;vel nenhuma escusa caso n&atilde;o tenha tido acesso a algum e-mail ou mensagem eletr&ocirc;nica em virtude dos recursos mencionados.</p>
<p>3.5. Ao acessar o&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>, os&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;declaram que ir&atilde;o respeitar todos os direitos de propriedade intelectual de titularidade da&nbsp;<strong>MEU TRATOR USADO</strong>, tal qual todos os direitos referentes a terceiros que porventura estejam, ou estiveram, de alguma forma, dispon&iacute;veis no&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>.</p>
<p>3.6. Os&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;devem manter o sigilo dos dados de sua conta de acesso em rela&ccedil;&atilde;o a terceiros, n&atilde;o divulgando ou compartilhando sua senha a quem quer que seja, sob pena de suportarem os &ocirc;nus dos atos praticados sob sua credencial, terem a exclus&atilde;o da conta e de ressarcirem os danos que sobrevierem dessa divulga&ccedil;&atilde;o indevida.</p>
<p>3.7. Caso o&nbsp;<strong>USU&Aacute;RIO</strong>&nbsp;suspeite que a confidencialidade de sua senha foi quebrada, este dever&aacute; proceder sua troca o mais r&aacute;pido poss&iacute;vel.</p>
<p>3.8. N&atilde;o &eacute; permitido o acesso as &aacute;reas de programa&ccedil;&atilde;o do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>, seu banco de dados ou qualquer outro conjunto de informa&ccedil;&otilde;es que fa&ccedil;a parte da atividade de&nbsp;<em>Webmastering</em>.</p>
<p>3.9. Tamb&eacute;m n&atilde;o &eacute; autorizado aos&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;realizar ou permitir engenharia reversa, nem traduzir, decompilar, copiar, modificar, reproduzir, alugar, sublicenciar, publicar, divulgar, transmitir, emprestar, distribuir ou, de outra maneira, dispor das ferramentas de consulta deste Portal e de suas funcionalidades.</p>
<p>3.10. No&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;&eacute; proibida a utiliza&ccedil;&atilde;o, de aplicativos&nbsp;<em>spider</em>, ou de minera&ccedil;&atilde;o de dados, de qualquer tipo ou esp&eacute;cie, al&eacute;m de outro aqui n&atilde;o tipificado, mas que atue de modo automatizado, tanto para realizar opera&ccedil;&otilde;es massificadas ou para quaisquer outras finalidades.</p>
<p>3.11. O descumprimento de quaisquer das obriga&ccedil;&otilde;es aqui estipuladas poder&aacute; acarretar na suspens&atilde;o das funcionalidades, sem preju&iacute;zo da responsabiliza&ccedil;&atilde;o por eventuais preju&iacute;zos causados, conforme previsto neste documento.</p>
<p>3.12. Visando &agrave; boa conviv&ecirc;ncia dentro do ambiente, sempre que um&nbsp;<strong>USU&Aacute;RIO</strong>&nbsp;puder publicar an&uacute;ncios, enviar coment&aacute;rios ou manifesta&ccedil;&otilde;es de pensamento a qualquer funcionalidade do&nbsp;<strong>Portal MEU TRATOR USADO</strong>, tais conte&uacute;dos poder&atilde;o n&atilde;o ser publicados ou exclu&iacute;dos, a qualquer tempo, sem pr&eacute;vio aviso e nenhum direito a indeniza&ccedil;&atilde;o a quem quer que seja, que contiverem:</p>
<ul>
<li>Ofensa &agrave; honra, imagem, reputa&ccedil;&atilde;o e dignidade de terceiros;</li>
<li>Pornografia, pornografia infantil ou outras modalidades de satisfa&ccedil;&atilde;o sexual;</li>
<li>Racismo ou discrimina&ccedil;&atilde;o de qualquer natureza;</li>
<li>Qualquer esp&eacute;cie de constrangimento ilegal, ass&eacute;dio ou aliciamento;</li>
<li>Manifesta viola&ccedil;&atilde;o a direito autoral ou direito de imagem;</li>
<li>Utiliza&ccedil;&atilde;o de marcas, s&iacute;mbolos, logotipos ou emblemas de terceiros;</li>
<li>Instiga&ccedil;&atilde;o ou apologia &agrave; pr&aacute;tica de crimes, como tr&aacute;fico ou uso de entorpecentes, estupro, homic&iacute;dio, estelionato, dentre outros;</li>
<li>Manifesta pr&aacute;tica de ato contr&aacute;rio &agrave; lei, &agrave; ordem p&uacute;blica ou aos bons costumes;</li>
<li>Uso da viol&ecirc;ncia, dissemina&ccedil;&atilde;o de &oacute;dio ou qualquer outra forma de agress&atilde;o ao bem-estar f&iacute;sico de algu&eacute;m;</li>
<li>Publicidade de qualquer tipo, especialmente &agrave;s que concorrerem com a atividade exercida pelo&nbsp;<strong>Portal MEU TRATOR USADO</strong>;</li>
<li>Erros ou suspeita de equ&iacute;vocos.</li>
</ul>
<p>3.13. A eventual remo&ccedil;&atilde;o, bloqueio ou suspens&atilde;o de qualquer conte&uacute;do ou funcionalidade do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;em decorr&ecirc;ncia de alguma reclama&ccedil;&atilde;o, dever&aacute; ser sempre compreendida como demonstra&ccedil;&atilde;o de boa-f&eacute; e inten&ccedil;&atilde;o de solu&ccedil;&atilde;o amig&aacute;vel de conflitos, jamais, como reconhecimento de culpa ou de qualquer infra&ccedil;&atilde;o pela&nbsp;<strong>MEU TRATOR USADO</strong>.</p>
<p>3.14. A&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;n&atilde;o envia e-mails ou outros tipos de comunica&ccedil;&atilde;o com links externos. Desta forma, caso o&nbsp;<strong>USU&Aacute;RIO</strong>&nbsp;receba alguma mensagem desse tipo, deve estar ciente dos riscos ao clicar no link, pois pode ser tentativa de fraude conhecida como&nbsp;<em>phishing</em>.</p>
<p>3.15. Na incid&ecirc;ncia de danos ao&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;ou a terceiros, o respons&aacute;vel se compromete a arcar com todas as obriga&ccedil;&otilde;es de indenizar o sujeito lesado.</p>
<p>3.16 Os&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;concordam em indenizar, defender e manter a&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;isenta de todos e quaisquer danos, perdas, responsabilidades, custos ou despesas, sendo justificado que a responsabilidade pela imagem, produto e negocia&ccedil;&atilde;o entre vendedor e comprador, tanto quanto suas poss&iacute;veis consequ&ecirc;ncias, preju&iacute;zos e condena&ccedil;&otilde;es ser&atilde;o apenas aplicados aos envolvidos, e a&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;n&atilde;o havendo qualquer responsabilidade da&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;neste sentido, devendo ser isenta de qualquer a&ccedil;&atilde;o judicial concernente, e, em casos de que seja acionada indevidamente, as partes dever&atilde;o arcar com as custas processuais atinentes</p>
<ol start="4">
<li><strong>Da Isen&ccedil;&atilde;o e Limita&ccedil;&otilde;es de Responsabilidade do MEU TRATOR USADO</strong></li>
</ol>
<p>4.1. Fica expressamente estabelecido que a&nbsp;<strong>MEU TRATOR USADO&nbsp;</strong> n&atilde;o tem a obriga&ccedil;&atilde;o de controlar todas as a&ccedil;&otilde;es executadas pelos&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;no uso da plataforma e, por conseguinte, a&nbsp;<strong>MEU TRATOR USADO&nbsp;</strong> n&atilde;o poder&aacute; ser responsabilizada por quaisquer atos de seus&nbsp;<strong>USU&Aacute;RIOS</strong>, inclusive de car&aacute;ter ilegal, imoral ou anti&eacute;tico, porventura perpetrados, cabendo &agrave; estes responderem pessoal e solidariamente por eventuais reclama&ccedil;&otilde;es de terceiros ou demandas judiciais, devendo manter a&nbsp;<strong>MEU TRATOR USADO&nbsp;</strong> livre de qualquer responsabilidade ou &ocirc;nus neste sentido.</p>
<p>4.1.1. Igualmente, a&nbsp;<strong>MEU TRATOR USADO&nbsp;</strong>n&atilde;o assume qualquer responsabilidade ou &ocirc;nus que estejam vinculados &agrave;s atividades dos&nbsp;<strong>USU&Aacute;RIOS&nbsp;</strong>no&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>, sobretudo as que envolvam a compra e venda de equipamentos usados, entre elas, devendo estes cumprirem uns em rela&ccedil;&atilde;o aos outros as obriga&ccedil;&otilde;es de ordem c&iacute;vel, fiscal, tribut&aacute;ria, dentre outras.</p>
<p>4.2. As informa&ccedil;&otilde;es disponibilizadas no&nbsp;<strong>PORTAL MEU TRATOR USADO&nbsp;</strong>n&atilde;o podem ser interpretadas como consultoria, n&atilde;o sendo a&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;respons&aacute;vel de qualquer forma pelas decis&otilde;es financeiras ou de aquisi&ccedil;&atilde;o de determinados produtos tomadas pelos&nbsp;<strong>USU&Aacute;RIOS</strong>.</p>
<p>4.3. O&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;n&atilde;o se responsabiliza por qualquer dano direto ou indireto ocasionado por eventos de terceiros, a exemplo, mas n&atilde;o se limitando a ataque de hackers, falhas no sistema, no servidor ou na conex&atilde;o &agrave; internet, inclusive por a&ccedil;&otilde;es de softwares maliciosos como v&iacute;rus, cavalos de Tr&oacute;ia, e outros que possam, de algum modo, danificar o equipamento ou a conex&atilde;o dos&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;em decorr&ecirc;ncia do acesso, utiliza&ccedil;&atilde;o ou navega&ccedil;&atilde;o no&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>, bem como a transfer&ecirc;ncia de dados, arquivos, imagens, textos, &aacute;udios ou v&iacute;deos contidos neste.</p>
<p>4.4. Os&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;n&atilde;o possuem qualquer direito para exigir a disponibilidade do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;conforme melhor lhes conv&ecirc;m, tampouco poder&atilde;o pleitear indeniza&ccedil;&atilde;o ou repara&ccedil;&atilde;o de danos em caso do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;permanecer fora do ar, independente da motiva&ccedil;&atilde;o.</p>
<p>4.5. A&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;n&atilde;o det&eacute;m qualquer responsabilidade pela navega&ccedil;&atilde;o dos&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;nos links externos contidos no&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>, sendo seus deveres a leitura dos Termos de Uso e Pol&iacute;tica de Privacidade do Portal acessado e agir conforme o determinado.</p>
<p>4.5.1. A&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;n&atilde;o verifica, controla, aprova ou garante a adequa&ccedil;&atilde;o ou exatid&atilde;o das informa&ccedil;&otilde;es ou dados disponibilizados em tais links, n&atilde;o sendo, portanto, respons&aacute;veis por preju&iacute;zos, perdas ou danos ocorridos pela visita de tais sites, cabendo ao interessado verificar a confiabilidade das informa&ccedil;&otilde;es e dados ali exibidos antes de tomar alguma decis&atilde;o ou praticar algum ato.</p>
<ol start="5">
<li><strong>Direitos Autorais e Propriedade Intelectual do Portal</strong></li>
</ol>
<p>5.1. O uso comercial da express&atilde;o &ldquo;<strong>MEU TRATOR USADO</strong>&rdquo; ou de palavras que se assemelham a estas, por&eacute;m com grafia diferenciada, como marcas, nomes empresariais ou nomes de dom&iacute;nio, al&eacute;m dos conte&uacute;dos das telas do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>, assim como os programas de computador, bancos de dados, redes e seus arquivos, s&atilde;o de propriedade da&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;e est&atilde;o resguardados pelas leis e tratados internacionais de prote&ccedil;&atilde;o &agrave; propriedade intelectual, incluindo, mas n&atilde;o se limitando, &agrave;s Leis Federais 9.609/1998, 9.610/1998, 9.279/1996 e 10.406/2002.</p>
<p>5.2. Ao acessar o&nbsp;<strong>PORTAL MEU TRATOR USADO,</strong>&nbsp;os&nbsp;<strong>USU&Aacute;RIOS&nbsp;</strong>declaram que ir&atilde;o respeitar todos os direitos de propriedade intelectual da&nbsp;<strong>MEU TRATOR USADO</strong>, incluindo, mas n&atilde;o se limitando, aos programas de computador, direitos autorais e direitos de propriedade industrial sobre as marcas, patentes, nomes de dom&iacute;nio, denomina&ccedil;&atilde;o social e desenhos industriais, depositados ou registrados em nome das empresas&nbsp;<strong>MEU TRATOR USADO</strong>, bem como de todos os direitos referentes a terceiros que porventura estejam, ou estiveram, de alguma forma, dispon&iacute;veis no&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>. O acesso ou uso das funcionalidades do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;n&atilde;o confere aos&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;quaisquer direitos ao uso dos nomes, t&iacute;tulos, palavras, frases, marcas, patentes, nomes de dom&iacute;nio, denomina&ccedil;&atilde;o social, obras liter&aacute;rias, art&iacute;sticas, l&iacute;tero-musicais, imagens, ilustra&ccedil;&otilde;es, dados e informa&ccedil;&otilde;es, dentre outras, que nele estejam ou estiveram dispon&iacute;veis.</p>
<p>5.3. A reprodu&ccedil;&atilde;o dos conte&uacute;dos descritos anteriormente est&aacute; proibida, salvo com pr&eacute;via autoriza&ccedil;&atilde;o por escrito da empresa titular de seus direitos patrimoniais ou caso se destinem ao uso exclusivamente pessoal e sem que em nenhuma circunst&acirc;ncia os&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;adquiram qualquer direito sobre os mesmos.</p>
<p>5.4. Os&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;assumem toda e qualquer responsabilidade, de car&aacute;ter civil e/ou criminal, pela utiliza&ccedil;&atilde;o indevida das informa&ccedil;&otilde;es, textos, gr&aacute;ficos, marcas, patentes, nomes de dom&iacute;nio, obras, imagens, logotipos, enfim, de todo e qualquer direito de propriedade intelectual ou industrial existentes no&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>.</p>
<p>5.5. Qualquer outro tipo de utiliza&ccedil;&atilde;o de material autorizado, inclusive para fins editoriais, comerciais ou publicit&aacute;rios, s&oacute; poder&aacute; ser feito na forma e mediante pr&eacute;vio e expresso consentimento da empresa titular de seus direitos patrimoniais. O uso comercial n&atilde;o autorizado poder&aacute; incorrer em infra&ccedil;&otilde;es c&iacute;veis e criminais.</p>
<p>5.6. Qualquer reutiliza&ccedil;&atilde;o de material autorizado dever&aacute; ser objeto de nova autoriza&ccedil;&atilde;o da empresa titular de seus direitos patrimoniais.</p>
<p>5.7. A autoriza&ccedil;&atilde;o conferida para utiliza&ccedil;&atilde;o do material solicitado n&atilde;o poder&aacute; ser transferida a terceiros, mesmo que vinculados ao sujeito autorizado.</p>
<p>5.8. A utiliza&ccedil;&atilde;o das funcionalidades oferecidas se dar&aacute; na forma de presta&ccedil;&atilde;o de servi&ccedil;os, n&atilde;o conferindo aos&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;nenhum direito sobre o programa de computador e/ou do banco de dados utilizados pela&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;ou de suas estruturas inform&aacute;ticas que sustentam as aplica&ccedil;&otilde;es do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>.</p>
<p>5.9. Quando os&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;enviam ao&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;quaisquer conte&uacute;dos, tais como, mas n&atilde;o se limitando a textos, coment&aacute;rios, v&iacute;deos, imagens, &aacute;udio e mensagens, declaram que det&eacute;m a titularidade dos direitos autorais sobre estes ou autoriza&ccedil;&atilde;o para sua utiliza&ccedil;&atilde;o e concedem &agrave;&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;licen&ccedil;a irrevog&aacute;vel, perp&eacute;tua, mundial, irrestrita, isenta de royalties e n&atilde;o exclusiva de reprodu&ccedil;&atilde;o, adapta&ccedil;&atilde;o, modifica&ccedil;&atilde;o, tradu&ccedil;&atilde;o, publica&ccedil;&atilde;o, distribui&ccedil;&atilde;o ou exibi&ccedil;&atilde;o no pr&oacute;prio site ou em ambientes digitais que lhe perten&ccedil;am e estejam vinculados &agrave;s atividades do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>, possibilitando a melhor utiliza&ccedil;&atilde;o da ferramenta ou ilustra&ccedil;&atilde;o de algum produto, servi&ccedil;o ou atividade por ele oferecidos.</p>
<ol start="6">
<li><strong>Privacidade dos usu&aacute;rios no Portal</strong></li>
</ol>
<p>6.1. A&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;possui documento pr&oacute;prio, denominado Pol&iacute;tica de Privacidade, que regula o tratamento dado &agrave;s informa&ccedil;&otilde;es coletadas no&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>.</p>
<p>6.2. A Pol&iacute;tica de Privacidade &eacute; parte integrante e insepar&aacute;vel dos Termos de Uso e Condi&ccedil;&otilde;es de Navega&ccedil;&atilde;o do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;e pode ser acessada no link encontrado em seu rodap&eacute;.</p>
<p>6.3. Caso alguma disposi&ccedil;&atilde;o da Pol&iacute;tica de Privacidade conflite com qualquer outra do presente documento, dever&aacute; prevalecer o descrito na norma mais espec&iacute;fica.</p>
<ol start="7">
<li><strong>Disposi&ccedil;&otilde;es Gerais</strong></li>
</ol>
<p>7.1. O atendimento dos&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;poder&aacute; ser realizado em seu Portal pelo link de &ldquo;Fale Conosco&rdquo; ou por meio dos outros canais de comunica&ccedil;&atilde;o disponibilizados e indicados no&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>.</p>
<p>7.2. Os&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;poder&atilde;o se valer dos canais de &ldquo;Fale Conosco&rdquo; toda vez que presenciarem ou verificarem conte&uacute;do impr&oacute;prio no&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>, seja ele notadamente il&iacute;cito ou contr&aacute;rio &agrave;s regras de uso aqui estipuladas.</p>
<p>7.2.1. A den&uacute;ncia ser&aacute; sigilosa e preservar&aacute; a identidade dos&nbsp;<strong>USU&Aacute;RIOS</strong>.</p>
<p>7.3. Os presentes Termos de Uso e Condi&ccedil;&otilde;es de Navega&ccedil;&atilde;o est&atilde;o sujeitos a constante melhoria e aprimoramento. Assim, a&nbsp;<strong>MEU TRATOR USADO</strong>&nbsp;se reserva o direito de modific&aacute;-los a qualquer momento, conforme a finalidade do&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;ou conveni&ecirc;ncia de sua controladora, tal qual para adequa&ccedil;&atilde;o e conformidade legal de disposi&ccedil;&atilde;o de lei ou norma que tenha for&ccedil;a jur&iacute;dica equivalente, cabendo aos&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;verificarem-nos sempre que efetuar o acesso ao&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>.</p>
<p>7.4. Ao navegar pelo&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;e utilizar suas funcionalidades, os&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;aceitam e obrigam-se pelos Termos de Uso e Condi&ccedil;&otilde;es de Navega&ccedil;&atilde;o e pela Pol&iacute;tica de Privacidade que se encontram vigentes na data de acesso. Por isso, &eacute; necess&aacute;rio e imprescind&iacute;vel que os&nbsp;<strong>USU&Aacute;RIOS</strong>&nbsp;se mantenham atualizados.</p>
<p>7.5. A toler&acirc;ncia do eventual descumprimento de quaisquer das cl&aacute;usulas e condi&ccedil;&otilde;es do presente instrumento n&atilde;o constituir&aacute; nova&ccedil;&atilde;o das obriga&ccedil;&otilde;es aqui estipuladas e tampouco impedir&aacute; ou inibir&aacute; a exigibilidade das mesmas a qualquer tempo.</p>
<p>7.6. Caso alguma disposi&ccedil;&atilde;o destes Termos de Uso ou da Pol&iacute;tica de Privacidade publicadas no&nbsp;<strong>PORTAL MEU TRATOR USADO</strong>&nbsp;for julgada inaplic&aacute;vel ou sem efeito, o restante de ambos os documentos continua a viger, sem a necessidade de medida judicial que declare tal assertiva.</p>
<p>7.7. Este Portal tem como base a data e hor&aacute;rios oficiais de Bras&iacute;lia.</p>
<ol start="8">
<li><strong>Lei aplic&aacute;vel e Jurisdi&ccedil;&atilde;o</strong></li>
</ol>
<p>8.1. Os Termos e Condi&ccedil;&otilde;es de Uso aqui descritos s&atilde;o interpretados segundo a legisla&ccedil;&atilde;o brasileira, no idioma portugu&ecirc;s, sendo eleito o Foro da Comarca de Ribeir&atilde;o Preto para dirimir qualquer lit&iacute;gio ou controv&eacute;rsia envolvendo o presente documento, salvo ressalva espec&iacute;fica de compet&ecirc;ncia pessoal, territorial ou funcional pela legisla&ccedil;&atilde;o aplic&aacute;vel.</p>
<p><strong>Atualiza&ccedil;&atilde;o:&nbsp;</strong>14 de dezembro de 2020.</p>
<p><strong>MEU TRATOR USADO TECNOLOGIA, PUBLICIDADE E INTERMEDIA&Ccedil;&Atilde;O DE NEG&Oacute;CIOS E SERVI&Ccedil;OS S.A.</strong></p>`

export const policy = `<h1 style="text-align: center;"><strong><br />Pol&iacute;tica de Privacidade Meu Trato Usado<br /></strong></h1>
<p><br />Nossa proposta de neg&oacute;cio &eacute; baseada em transpar&ecirc;ncia. A transpar&ecirc;ncia est&aacute; presente em nossa rela&ccedil;&atilde;o com nossos clientes, com o mercado, nossos colaboradores, fornecedores, parceiros e acionistas. Al&eacute;m da transpar&ecirc;ncia, prezamos pela &eacute;tica, coopera&ccedil;&atilde;o, responsabilidade social, sustentabilidade, valoriza&ccedil;&atilde;o dos colaboradores e crescimento e rentabilidade. S&atilde;o com esses princ&iacute;pios que norteamos nossos neg&oacute;cios. Respeito &agrave; sua privacidade, respeito aos seus direitos e sobretudo, respeito a voc&ecirc; que, de alguma maneira, se relaciona conosco atrav&eacute;s de nossos produtos, servi&ccedil;os ou algum de nossos canais existentes.</p>
<p>Por favor, recomendamos que a pol&iacute;tica de privacidade abaixo seja lida com aten&ccedil;&atilde;o. Ela descreve como s&atilde;o tratados os dados pessoais fornecidos por voc&ecirc; ao acessar e utilizar o site. Ao acessar, utilizar ou navegar pelo site, voc&ecirc; aceita as disposi&ccedil;&otilde;es desta pol&iacute;tica de privacidade e concorda em vincular-se &agrave;s suas condi&ccedil;&otilde;es, de forma livre e espont&acirc;nea. Ao usar o site, voc&ecirc; autoriza a coleta e uso de informa&ccedil;&otilde;es conforme estabelecido nesta pol&iacute;tica de privacidade. Ao utilizar os nossos Servi&ccedil;os, o usu&aacute;rio aceita e concorda com todos os termos e condi&ccedil;&otilde;es expostas que se encontram vigentes na data.</p>
<p>Alertamos que estes Termos e Condi&ccedil;&otilde;es de Uso poder&atilde;o ser modificados a qualquer momento pelo Meu Trator Usado, em virtude de altera&ccedil;&otilde;es na legisla&ccedil;&atilde;o ou nos Servi&ccedil;os, em decorr&ecirc;ncia da utiliza&ccedil;&atilde;o de novas ferramentas tecnol&oacute;gicas ou, ainda, sempre que, a exclusivo crit&eacute;rio do Meu Trator Usado, tais altera&ccedil;&otilde;es se fa&ccedil;am necess&aacute;rias, haver&aacute; a necessidade de aceite destes novos termos por parte do usu&aacute;rio. A utiliza&ccedil;&atilde;o dos Servi&ccedil;os online disponibilizados pelo Meu Trator Usado por qualquer usu&aacute;rio implicar&aacute; em expressa aceita&ccedil;&atilde;o destes Termos e Condi&ccedil;&otilde;es de Uso.</p>
<p><strong>O QUE ENTENDEMOS COMO PRIVACIDADE</strong></p>
<p>Definimos privacidade como o direto de todos em n&atilde;o ser monitorado, n&atilde;o ser registrado e de n&atilde;o ser reconhecido. Baseada nisso, criamos nossos produtos e servi&ccedil;os de forma a garantir que voc&ecirc; se relacione conosco de maneira leg&iacute;tima, &eacute;tica e adequada, sempre respeitando todas as partes envolvidas.</p>
<p><strong>DEFINI&Ccedil;&Atilde;O DE &ldquo;MEU TRATOR USADO&rdquo; E &ldquo;CLIENTES&rdquo;</strong></p>
<p>No escopo desta pol&iacute;tica chamamos "MEU TRATO USADO" a tudo o que diga respeito ao universo organizacional, ou seja, s&atilde;o nossos colaboradores no exerc&iacute;cio de suas fun&ccedil;&otilde;es, nossos produtos em opera&ccedil;&atilde;o, o per&iacute;metro de nossos escrit&oacute;rios e tudo o que seja parte da empresa Meu Trator Usado, suas coligadas ou parceiras de neg&oacute;cio quando em exerc&iacute;cio desta parceria. Tamb&eacute;m neste documento, chamamos "CLIENTE" a todas as pessoas naturais, titulares de dados tratados no escopo que de alguma forma se relacionem conosco. Sejam eles acionistas, colaboradores, clientes, terceiros, visitantes, fornecedores ou qualquer pessoa que tenha alguma rela&ccedil;&atilde;o conosco que esteja englobada pelos termos desta pol&iacute;tica.</p>
<p><strong>ESCOPO DESTA POL&Iacute;TICA</strong></p>
<p>Esta Pol&iacute;tica de Prote&ccedil;&atilde;o de Dados se aplica &agrave; organiza&ccedil;&atilde;o da empresa Meu Trato Usado, e engloba todas as nossas atividades, dimens&otilde;es e aplica&ccedil;&otilde;es em todo territ&oacute;rio em que operamos.</p>
<p>Esta pol&iacute;tica se aplica ao processamento de dados pessoais que s&atilde;o fornecidos para que possamos operar em nossos neg&oacute;cios, produtos e servi&ccedil;os e viabilizar uma melhor experi&ecirc;ncia para voc&ecirc; dentro da plataforma de nossos produtos.</p>
<p><strong>DEFINI&Ccedil;&Atilde;O DE "DADOS PESSOAIS"</strong></p>
<p>Entendemos "dados pessoais" como sendo todos os dados que processamos, de forma direta ou indireta, que torne a pessoa natural identificada ou identific&aacute;vel.</p>
<p><strong>QUAL IMPORT&Acirc;NCIA DAMOS A LEI</strong></p>
<p>N&oacute;s embasamos esta Pol&iacute;tica de Privacidade na Lei N&ordm; 13.709/18 , ou Lei Geral de Prote&ccedil;&atilde;o de Dados (LGPD), a qual estabelece regras sobre a coleta, armazenamento, tratamento e compartilhamento de dados pessoais, sempre visando a maior prote&ccedil;&atilde;o dos titulares desses dados, ou seja, voc&ecirc;.</p>
<p>Sendo assim, nos comprometemos a seguir as diretrizes da legisla&ccedil;&atilde;o que se aplica em todo territ&oacute;rio nacional a fim de garantir que todos os dados pessoais coletados e processados por n&oacute;s ser&atilde;o tratados de acordo com os termos da LGPD, salvo casos espec&iacute;ficos desde que sejam justificados pelas bases legais cab&iacute;veis.</p>
<p><strong>&nbsp;</strong></p>
<p><strong>POR QUE PRECISAMOS DE SEUS DADOS?</strong></p>
<p>A primeira coisa que queremos que voc&ecirc; saiba &eacute; que n&atilde;o processamos seus dados sem que haja uma real necessidade e uma base legal para isso. Assim, os dados podem ser processados quando:</p>
<ul>
<li>seja necess&aacute;rio a execu&ccedil;&atilde;o de um contrato do qual voc&ecirc; seja parte essencial;</li>
<li>seja necess&aacute;rio o cumprimento de uma obriga&ccedil;&atilde;o legal;</li>
<li>ou ent&atilde;o em a&ccedil;&otilde;es internas, desde que tenhamos o seu consentimento pr&eacute;vio.</li>
</ul>
<p>Podemos processar seus dados para fins de nossos interesses leg&iacute;timos, mas nunca quando esses interesses ferirem seus pr&oacute;prios interesses, direitos ou liberdades fundamentais. Contudo, sempre que necess&aacute;rio e aplic&aacute;vel por lei, pediremos seu consentimento antes de fazer a coleta de seus dados.</p>
<p><strong>QUAIS DADOS COLETAMOS</strong></p>
<p>Nos comprometemos com os princ&iacute;pios da FINALIDADE, ADEQUA&Ccedil;&Atilde;O e NECESSIDADE, segundo rege a Lei Geral de Prote&ccedil;&atilde;o de Dados. Assim nunca coletamos dados al&eacute;m daqueles que s&atilde;o estritamente necess&aacute;rios para a realiza&ccedil;&atilde;o dos neg&oacute;cios a que esses dados se destinam. Garantimos que estes dados ser&atilde;o utilizados para o fim declarado no momento da coleta e que o tratamento aplicado durante todo o ciclo de vida destes dados &eacute; adequado &agrave; sua finalidade.</p>
<p>Coletamos dados pessoais de nossos colaboradores, acionistas e parceiros comerciais. Entre estes dados est&atilde;o dados de contato como: nome, telefone, celular e e-mail, dados de localiza&ccedil;&atilde;o como rua, CEP, bairro, cidade e UF.</p>
<p>Tratamos dados referentes aos equipamentos que s&atilde;o avaliados em nossa plataforma, como: marca, modelo, cor, chassi, estado de conserva&ccedil;&atilde;o de v&aacute;rios componentes e demais informa&ccedil;&otilde;es pertinentes para uma avalia&ccedil;&atilde;o satisfat&oacute;ria. Ainda podemos tratar dados do propriet&aacute;rio do equipamento, como: nome, CPF, e-mail, telefone, celular, logradouro, cep, detalhes de endere&ccedil;o, bairro, cidade. Estes dados s&atilde;o coletados por nossos clientes nos exerc&iacute;cios da utiliza&ccedil;&atilde;o de nossos produtos de softwares e podem variar segundo as configura&ccedil;&otilde;es exercidas por estes mesmos clientes.</p>
<p>Ainda podemos coletar dados de contato, para fins de campanhas de marketing e demais promo&ccedil;&otilde;es destinadas &agrave; clientes assinantes de nossos produtos; coletar dados referentes ao hist&oacute;rico de atendimento em nosso sistema de Help Desk e CRM e coletar dados para emiss&atilde;o de notas fiscais segundo determina o conjunto de normas, s&uacute;mulas e leis fiscais vigentes.</p>
<p>No entanto &eacute; imprescind&iacute;vel declarar que nenhum desses dados &eacute; ou ser&aacute; utilizado de forma diversa daquela a que &eacute; destinado sempre segundo o consentimento e direito do titular ou segundo o fundamento legal que embasa seu tratamento.</p>
<p><strong>POR QUANTO TEMPO FICAMOS COM SEUS DADOS</strong></p>
<p>Cada conjunto de dados fica em nosso poder apenas o tempo necess&aacute;rio para atingir o objetivo a que se destina. Sendo assim, o tempo que mantemos seus dados varia de acordo com o tratamento a que esses dados est&atilde;o destinados. No entanto, sempre que poss&iacute;vel, e quando a legisla&ccedil;&atilde;o vigente permitir, voc&ecirc; pode exercer seu direito de se opor ao processamento ou seu direito de ser esquecido.</p>
<p>As informa&ccedil;&otilde;es precisas sobre o tempo de vida, o tratamento e destino dos dados que recolhemos s&atilde;o e sempre ser&atilde;o informados no momento de sua coleta, para cada dado ou conjunto de dados especificamente coletados.</p>
<p><strong>QUANDO E COMO UTILIZAMOS COOKIES</strong></p>
<p>Cookies s&atilde;o pequenos arquivos de texto que armazenam em seu dispositivo dados da p&aacute;gina que voc&ecirc; est&aacute; visitando. N&oacute;s fazemos uso de cookies para registrar sua sess&atilde;o, seu tr&aacute;fego em nossos produtos e tornar a sua experi&ecirc;ncia melhor e mais personalizada em nossos sites. Os cookies aprimoram e permitem que sua experi&ecirc;ncia online seja diferenciada, salvando suas prefer&ecirc;ncias enquanto voc&ecirc; visita e navega em nossos sites.</p>
<p>Cada um de nossos sites ou produtos disp&otilde;e de uma pol&iacute;tica de cookies pr&oacute;pria, sempre acess&iacute;vel na regi&atilde;o do rodap&eacute;. Nesta pol&iacute;tica constam detalhadamente quais cookies, por quanto tempo e por qu&ecirc; s&atilde;o armazenados em seu dispositivo. Nesta mesma regi&atilde;o voc&ecirc; pode se opor ou consentir (a qualquer tempo), no armazenamento de cada um dos cookies e saber exatamente o motivo e por quanto tempo este cookie estar&aacute; dispon&iacute;vel.</p>
<p><strong>QUANDO, COMO E PARA QUEM DIVULGAMOS SEUS DADOS</strong></p>
<p>Os dados que coletamos ou processamos, tendo em vista a natureza dos neg&oacute;cios que realizamos, podem ser compartilhados com nossos colaboradores ou parceiros comerciais. Sempre respeitando a integridade, os princ&iacute;pios da LGPD, o bom senso e, principalmente, o respeito a voc&ecirc;, titular do dado.</p>
<p>Em nenhuma hip&oacute;tese n&oacute;s vendemos seus dados e n&atilde;o compartilhamos com ningu&eacute;m que n&atilde;o esteja definido no escopo "n&oacute;s". No entanto, esses dados podem ser utilizados para realiza&ccedil;&atilde;o de an&aacute;lises estat&iacute;sticas an&ocirc;nimas e os resultados dessas an&aacute;lises (sempre an&ocirc;nimas) podem ser objeto de pesquisa e de comercializa&ccedil;&atilde;o. Por&eacute;m, os objetos desse tratamento n&atilde;o se identificam, nem de forma direta ou indireta uma pessoa natural, ou seja, n&atilde;o s&atilde;o considerados dados pessoais.</p>
<p><strong>O QUE FAZEMOS PARA PROTEGER SEUS DADOS PESSOAIS</strong></p>
<p>Para n&oacute;s, prote&ccedil;&atilde;o de dados &eacute; coisa s&eacute;ria. Este &eacute; um de nossos preceitos fundamentais, por isso empregamos uma s&eacute;rie de tecnologias, metodologias e procedimentos para garantir sua privacidade e a integridade dos dados que voc&ecirc; nos confiou. Nossos dados s&atilde;o armazenados em Data Centers certificados e em conformidade com LGPD e a GDPR da Uni&atilde;o Europeia e demais certifica&ccedil;&otilde;es relevantes.</p>
<p>Al&eacute;m disso, contamos com trilhas de treinamentos obrigat&oacute;rios referentes ao assunto para todos nossos colaboradores e parceiros, justamente para garantir que todas as pessoas que de alguma forma possam manipular ou tratar seus dados estejam aptos e conscientizados da import&acirc;ncia da seriedade e dedica&ccedil;&atilde;o em rela&ccedil;&atilde;o aos procedimentos de nossa Pol&iacute;tica de Seguran&ccedil;a da Informa&ccedil;&atilde;o.</p>
<p><strong>COMO TRATAMOS DADOS DE MENORES</strong></p>
<p>A plataforma do portal Meu Trato Usado n&atilde;o coleta nem faz tratamento de dados de menores de idade. Os acessos e contas podem ser operados somente por pessoas maiores de 18 anos e o cadastro no site&nbsp;<a href="https://www.meutratorusado.com.br/">https://www.meutratorusado.com.br/</a>&nbsp;pode ser criado somente por pessoas jur&iacute;dicas, f&iacute;sicas ou produtores rurais que se encontram em total conformidade com a Receita Federal do Brasil.</p>
<p><strong>SEUS DIREITOS E DEVERES</strong></p>
<p>Nos comprometemos em garantir os seus direitos, sempre com o apoio da legisla&ccedil;&atilde;o vigente a fim de proporcionar a m&aacute;xima prote&ccedil;&atilde;o dos seus dados pessoais.</p>
<p>S&Atilde;O SEUS DIREITOS:</p>
<ul>
<li>DIREITO DE ACESSO: voc&ecirc; pode solicitar acesso aos seus dados pessoais, bem como a corre&ccedil;&atilde;o de dados imprecisos ou incompletos. Voc&ecirc; tamb&eacute;m pode solicitar qualquer informa&ccedil;&atilde;o sobre a fonte dos dados e uma c&oacute;pia destes dados quando aplic&aacute;vel.</li>
<li>DIREITO DE SER ESQUECIDO: voc&ecirc; pode solicitar a exclus&atilde;o dos seus dados em nossa base, quando:</li>
<ol>
<li>os dados n&atilde;o forem mais necess&aacute;rios;</li>
<li>voc&ecirc; n&atilde;o possuir mais interesse em nossos produtos;</li>
<li>voc&ecirc; optar por retirar o consentimento previamente dado a n&oacute;s;</li>
<li>voc&ecirc; se opor ao processamento dos seus dados por meios automatizados que utilizam especifica&ccedil;&otilde;es t&eacute;cnicas;</li>
<li>existir uma obriga&ccedil;&atilde;o legal para o apagamento dos seus dados pessoais;</li>
<li>o apagamento dos dados pessoais for necess&aacute;rio para garantir a conformidade &agrave;s leis aplic&aacute;veis.</li>
</ol>
</ul>
<p>Aqui, n&oacute;s tamb&eacute;m nos asseguramos que, se necess&aacute;rio, podemos manter os dados pessoais, desde que haja o respaldo de bases legais vigentes.</p>
<ul>
<li>DIREITO A RESTRI&Ccedil;&Atilde;O DE PROCESSAMENTO: voc&ecirc; pode restringir o uso dos seus dados pessoais, desde que haja uma fundamenta&ccedil;&atilde;o legal e/ou coerente para isso.</li>
<li>DIREITO &Agrave; OPOSI&Ccedil;&Atilde;O PARA MARKETING DIRETO: voc&ecirc; pode, a qualquer momento, fazer uso do seu direito de &ldquo;optar por n&atilde;o&rdquo; fazer parte dos processamentos que envolvem campanhas de marketing, cria&ccedil;&atilde;o de perfis ou comunica&ccedil;&otilde;es diretas. Mesmo que voc&ecirc; tenha dado o consentimento pr&eacute;vio.</li>
<li>DIREITO A PORTABILIDADE: quando aplic&aacute;vel, voc&ecirc; pode solicitar a n&oacute;s a portabilidade dos seus dados pessoais que foram processados, de forma estruturada e de f&aacute;cil acesso, a fim de transferir a outro Controlador de dados as informa&ccedil;&otilde;es coletadas por n&oacute;s.</li>
</ul>
<p>MAS S&Atilde;O SEUS DEVERES:</p>
<ul>
<li>Manter seus dados sempre atualizados em nossa plataforma, a fim de facilitar o contato entre as transa&ccedil;&otilde;es efetuadas exclusivamente por ela e para fins de contato pelo nosso Suporte T&eacute;cnico ou Atendimento ao Lojista;</li>
<li>O cadastro dentro do portal Meu Trator Usado &eacute; individual e intransfer&iacute;vel. Sendo assim &eacute; de total responsabilidade do usu&aacute;rio criar uma senha forte para acesso, bem como n&atilde;o compartilhar a senha com terceiros, a fim de evitar constrangimentos e sistemas de fraudes.</li>
</ul>
<p><strong>ACESSO A CONTE&Uacute;DO RESTRITO E SUSPENS&Atilde;O DE ACESSO</strong></p>
<p>Alguns Servi&ccedil;os est&atilde;o dispon&iacute;veis em conte&uacute;do aberto e fechado. Quando o acesso a conte&uacute;do for restrito, ser&aacute; necess&aacute;rio pr&eacute;vio cadastro do usu&aacute;rio e o acesso ao ambiente por meio de login e senha. Considerando que voc&ecirc; &eacute; respons&aacute;vel pela veracidade das informa&ccedil;&otilde;es cadastradas, informamos que o cadastro de informa&ccedil;&otilde;es falsas pode gerar inconsist&ecirc;ncia na presta&ccedil;&atilde;o dos Servi&ccedil;os, bem como impactar ou interromper o seu acesso.</p>
<p>A qualquer tempo, sem aviso pr&eacute;vio, o Meu Trato Usado poder&aacute; suspender, cancelar ou interromper o acesso aos Servi&ccedil;os, respeitadas as condi&ccedil;&otilde;es da legisla&ccedil;&atilde;o aplic&aacute;vel.</p>
<p>O Meu Trator Usado n&atilde;o se responsabiliza por eventuais danos e/ou problemas decorrentes da demora, interrup&ccedil;&atilde;o ou bloqueio nas transmiss&otilde;es de dados decorrentes da conex&atilde;o de internet do usu&aacute;rio.</p>
<p><strong>ATUALIZA&Ccedil;&Otilde;ES</strong></p>
<p>Nos comprometemos a manter esta pol&iacute;tica sempre coerente &agrave; legisla&ccedil;&atilde;o e atualizada. Fazemos uso do direito de atualiz&aacute;-la &agrave; medida que nossos neg&oacute;cios ou requisitos legais sejam alterados. Caso essas altera&ccedil;&otilde;es sejam de grande impacto ou interfiram, de qualquer maneira, nos dados previamente coletados, todos os envolvidos ser&atilde;o avisados da forma mais pertinente e cab&iacute;vel no momento.</p>
<p><strong>D&Uacute;VIDAS</strong></p>
<p>Caso tenha persistido alguma d&uacute;vida referente &agrave; coleta e processamento de seus dados pessoais, dispomos de um canal exclusivo para que voc&ecirc; possa entrar em contato com nosso Encarregado de Dados. Basta enviar um e-mail para&nbsp;comercial<a href="mailto:wsz@meutratousado.com.br">@meutratousado.com.br</a>&nbsp;que teremos o maior prazer de ajud&aacute;-lo!</p>
<p>MEU TRATO USADO TECNOLOGIA E SERVI&Ccedil;OS ADMINISTRATIVOS LTDA. inscrita no CNPJ/MF sob o n&ordm; 39.592.054/0001-29, com sede na Avenida Bar&atilde;o do Bananal, Jardim Anhanguera, Ribeir&atilde;o Preto / SP, CEP 14.092-000.</p>`
